### ISSUE TITLE
log on nexus 5

### ISSUE THREAD

**Issue by kikuchitakuro** [adithya321/Companion-for-Band#1]
My nexus 5 cannot log data of microsoft band 2. I granted storage permission  successfully because photos could be saved through camera tile.

**Comment by adithya321** [comment]
That's odd! Try toggling the log switch in app and checking the storage switch in app permissions page in settings.

**Comment by luicap** [comment]
I've The same problem on my LG 320, the folders permissions are ok and the switch is on.any idea, thank you 
L.

**Comment by kikuchitakuro** [comment]
Logging has succeeded since previous update at my Nexus 5. Thank you.
