### ISSUE TITLE
Feature Request: Add "IMG_" prefix to images taken with camera tile

### ISSUE THREAD

**Issue by xnonamefacex** [adithya321/Companion-for-Band#12]
I would really like it if you could add "IMG_" prefix to the images taken with the camera tile from the band.  It seems that this prefix is required for the images to be recognized as photos in the default (and some non-default) image viewers I have on my phone -- Photos, File Manager.  

I changed the storage location to be the same location as the default camera to see if that would allow the photos to get recognized, no luck.  I manually renamed the photo to add "IMG_" to the beginning of the filename the camera tile generated and this allowed it to be picked up and recognized by all of the photo apps.

I believe this is the correct fix, but if there is another way that allows the default "photos" app to pick up the new photos and back them up then that is acceptable as well.

Running Android 6.0.1 on a Google Nexus 5

Thanks!

**Comment by adithya321** [comment]
Thank you for the suggestion.

**Comment by xnonamefacex** [comment]
Looks like my initial assessment may have been incorrect.  renaming it to ANYTHING causes the default apps to pick it up (as does rebooting the phone) so it appears that something needs to trigger to just scan/index the new pictures.

http://stackoverflow.com/questions/18183219/cant-see-pictures-saved-in-a-specific-folder
http://stackoverflow.com/questions/25401685/camera-intent-picture-missing-in-gallery?rq=1

Found some info here too that seemed to suggest that as well.

**Comment by adithya321** [comment]
Fixed in [v2.9.2](https://github.com/adithya321/Companion-for-Band/releases/tag/v2.9.2). Thanks!
