### ISSUE TITLE
Camera & Possible new Feature 

### ISSUE THREAD

**Issue by ExistentialNerd** [adithya321/Companion-for-Band#16]
No matter what I do the camera feature will not work and display a permission denied pop-up. Also, would there be anyway to create a voice commands feature or speak to reply option using the band's microphone?

Debug info:
 OS Version: 3.18.20-7722939(G930VVRS2APF2)
 OS API Level: 23
 Device: heroqltevzw
 Model (and Product): SM-G930V (heroqltevzw)
 RELEASE: 6.0.1
 BRAND: Verizon
 DISPLAY: MMB29M.G930VVRS2APF2
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: qcom
 MANUFACTURER: samsung

Extra Info: Nothing to show.

**Comment by adithya321** [comment]
Go to 'App info' settings page and allow permission for 'Camera'. 
No, Microsoft has not exposed the microphone for developers to use.
