### ISSUE TITLE
Log issue

### ISSUE THREAD

**Issue by Groundsea** [adithya321/Companion-for-Band#18]
I enabled the log heart beat sensor, but it seemed when the phone's screen get off about 10 mins, the green lights on the back of band will get off, and can't record the heart rate any longer.
Please help to find the reason, thank you very much!

Debug info:
 OS Version: 3.18.20-perf-g691aba0-00807-gca53819(20160722.151451)
 OS API Level: 23
 Device: ailsa_ii
 Model (and Product): ZTE A2017 (P996A03)
 RELEASE: 6.0.1
 BRAND: ZTE
 DISPLAY: ZTE_A2017V1.0.0B07
 CPU_ABI: arm64-v8a
 CPU_ABI2: 
 HARDWARE: qcom
 MANUFACTURER: ZTE

Extra Info: Nothing to show.

**Comment by adithya321** [comment]
Have you enabled the 'Log in background' option?

**Comment by Groundsea** [comment]
Yes, I have enabled it. And I found the reason, it is because my phone will automatically stop the background app in ten miniutes. When I tune off this setting, it works fine. Thank you very much!
