### ISSUE TITLE
app doesnt owrk anymore

### ISSUE THREAD

**Issue by slicer101** [adithya321/Companion-for-Band#2]
I have a LG G4 android 6.0. Wuth MS Band 2The app worked fine a cupple of months ago. Sensors worked I could change the theme etc. Now it says that it can not connect to the band. The other thing is I had my band changed due to malfunction.

**Comment by adithya321** [comment]
Try deleting the old band from Bluetooth paired devices list.

**Comment by slicer101** [comment]
Thank you that actualy solved the problem Ill be changing my raiting on
google play from 2\*  back to 5*
