### ISSUE TITLE
Barcode on Band 2

### ISSUE THREAD

**Issue by texabrams** [adithya321/Companion-for-Band#4]
I can send the tile and barcode to the Band 2 but get a black screen when viewing barcode.

**Comment by adithya321** [comment]
I have fixed it in this update hopefully. Let me know if it works now.

**Comment by texabrams** [comment]
The bar codes do show up now on my band 2.  Thanks.

**Comment by texabrams** [comment]
It does work now but for some reason when I enter all 12 digits, I get a
white screen on the band.  When I use 11 digits, I get the barcode.

**Comment by adithya321** [comment]
[http://developer.microsoftband.com/content/docs/microsoft%20band%20sdk.pdf](url)

8.6.2 Supported character set for CODE39 barcodes
On both Microsoft Band 1 and Microsoft Band 2, each character must be a valid Code 39 character: 0-9, A-Z, space, $, %, +, -, /, or . (period). The Band will allow a string of up to 39 characters to be assigned, but 

> because of the Band screen width and resolution, the effective upper limit that can be rendered is 12 characters. 

Like with PDF417 barcodes, if the Band is unable to render the entire CODE39 Barcode content within the space
available to the element in the layout, the available space will be blank. That is, if the complete Barcode cannot be
displayed, no portion of the Barcode will be displayed.
