### ISSUE TITLE
Log in background not working

### ISSUE THREAD

**Issue by dustwindbun** [adithya321/Companion-for-Band#6]
Hi! For some reason the app won't log in the background even though I have that option chosen. I can see it in my recent apps, but nothing gets added to the files unless I open the app again. I'm using a Band 2 and an HTC phone running Android 6.0 (and no task manager apps or anything like that.)

**Comment by adithya321** [comment]
When opening the app for the first time, I've set the 'Log in Background' switch on but set the value as off in code. So toggling the switch off and on once will fix this issue.

**Comment by adithya321** [comment]
Fixed the issue in v2.5.4.

**Comment by dustwindbun** [comment]
Working now, thanks!
